### ISSUE TITLE
Intégrer les corrections de Stéphane Deschamps

### ISSUE THREAD

**Issue by desbenoit** [t13h37/feedback-desbenoit-icones#11]
11:54
Salut Seb,

Ci-dessous la lecture que j'ai faite il y a un an. Mais bno, mieux vaut tard que jamais. ;)

---

Nous allons désormais nous intéresser aux spécificités de chacun de ses

-> de ces 

---

d’autant plus qu’il varie selon si ces signes sont imprimés ou sur un écran ! En

-> selon que 

---

Au début ils ne « lisent » pas leur nom, ils le “reconnaissent” par la forme des lettres

-> Cohérence des guillemets, ça doit être «» ou “” partout, mais pas l'un ou l'autre. 

---

Le pictogramme sur lequel se base ces deux types particuliers d’icônes

-> se basent 

---

Les packs d’icônes sont de formidables outils en ce qui concerne la cohérence graphique d’un jeu d’icônes, nous y reviendrons. En revanche, en ce qui concerne les messages portés, ils sont à utiliser avec autant de précaution qu’un baril de nitroglycérine sur une piste kazakh.

-> non rien, j'ai juste bien rigolé :)

---

Cette exemple démontre au passage que les icônes

-> Cet exemple 

---

quelque soit leur culture ou leur langue, par

-> quelle que soit 

---

signe ne sort jamais indemne de ces indispensables tests car, quelque soit notre méthodologie et notre expérience, il reste toujours

-> quelles que soient 

---

Que ce soit nos collègues de travail, notre compagnon, nos parents…

-> Que ce soient 

---

Le temps de compréhension et les différentes observations que nous aurons faites lors des tests vont nous permettre d’évaluer les différents pictogrammes. Ce processus de mise en concurrence est un bon moyen de voir la pertinence de ceux-ci dans le cas où ils sont des choix

-> Là je n'ai pas compris cette dernière phrase 

---

Parfois un simple détail peut changer complètement le compréhension d’un pictogramme.

-> la compréhension

**Comment by pouipouidesign** [comment]
Hello, bien vu !
J'ai fait les corrections dans les sources, mais voudrais-tu en profiter pour faire des ajouts (cf. tickets #9 et #10 ) avant qu'on re-génère tout ça ??

**Comment by desbenoit** [comment]
Hello Marie, 
Je me mets au travail ce soir pour que vous ayez de quoi préparer cela. 
:)

**Comment by desbenoit** [comment]
Hello Marie,

J'ai fais les modifications dans le BitBucket avec l'ajout de deux vraies
parties sur les dark patterns et sur l'application de style. Je vous laisse
relire cela avant d'ajouter et mettre les illustrations également !

Bises

Le mar. 7 avr. 2015 à 10:39, Marie Alhomme notifications@github.com a
écrit :

**Comment by pouipouidesign** [comment]
v1.3 poussée hier !
Encore merci :)
