### ISSUE TITLE
Certains symboles manquants dans l'extrait 

### ISSUE THREAD

**Issue by borisschapira** [t13h37/feedback-desbenoit-icones#2]
Dans l'extrait PDF visible sur http://envoitu.re/ligne-essai/design-icones-manuel/extrait-sdesbenoit-design-icones.pdf, il manque des symboles. Par exemple dans la phrase : "Ainsi la forme ✔ ne représente pas un 
certain trait de crayon mais la validation.", le symbole "check" n'est pas visible sur : 
- LG G2 (Android KitKat), QuickOffice v6.3.1.041
- Chrome 34.0.1847.137 m pour Windows
- Windows 8.1, application Reader de PDF par défaut
- Adobe Reader 11.0.07 sous Windows

**Comment by pouipouidesign** [comment]
Argh, bien vu... C'est un problème de typo a priori, on se mets dessus ASAP et on vous tient au courant !!

**Comment by desbenoit** [comment]
Merci pour le retour Boris !

**Comment by borisschapira** [comment]
C'est très intéressé, pour être honnête. 

J'aurais préféré une version papier pour éviter les problèmes de ce genre mais comme je suis impatient, j'ai quand même DL le PDF pour voir s'il s'affichait sur mon Kindle, en me disant que le PDF d'extrait avait sûrement été généré par un process peu éloigné du process de génération final.

J'attends donc que ça soit corrigé pour passer à la caisse :)

**Comment by desbenoit** [comment]
Super, 

Pour le Kindle, tu as la version ePub également qui s'affichera correctement.

**Comment by borisschapira** [comment]
Avec des arguments comme ça, pas d'autre solution que de faire chauffer la CB :)

**Comment by pouipouidesign** [comment]
Merci pour le retour, et l'achat :)
On est dessus, c'est assez sioux pour tout dire...
On vous tient au courant asap !

**Comment by pouipouidesign** [comment]
On est toujours dessus, mais ça nous oblige à faire un gros travail de refonte sur l'outil de génération donc ça prend un peu plus de temps que prévu...
On continue de vous tenir au courant !

**Comment by pouipouidesign** [comment]
Plop, a priori c'est donc corrigé et envoyé à tous nos acheteurs ! Je ferme mais n'hésitez pas à rouvrir si toujours des soucis demain :)

**Comment by borisschapira** [comment]
Coucou, l'extrait de lecture en ligne http://boutique.letrainde13h37.fr/products/design-icones-le-manuel-sebastien-desbenoit est toujours cassé, par contre.
