### ISSUE TITLE
Coquilles

### ISSUE THREAD

**Issue by P45QU10U** [t13h37/feedback-desbenoit-icones#3]
Page 20-21 :

[...] ou une émotion « Vous m’énervez » en pointant l’icône 
correspondant*.
- correspondante.

Page 31, Encadré : Des icônes et des marques : 

[...] Le pictogramme sur lequel se base ces deux types particuliers d’icônes doit
s’appuyer uniquement sur le logotype du produit. Un travail plus léger peut
être réaliser\* sur le contexte et l’étape de pictogramme n’est pas réellement
nécessaire : ces deux phases ont normalement été réalisées lors de la
conception de l’identité visuelle. [...]
- réalisé.

Page 43 : 

[...] Un marteau n’aura pas la même formes\* si notre interface est
destinée à des maçons ou à des orfèvres. [...]
- forme.

Page 49 : 

[...] Toutefois, nous pouvons détailler le chemin
d’une bonne recherche de pictogramme. Que nous en soyons conscient\* ou
non, notre choix se fera toujours en fonction de notre propre contexte. Pour
éviter cet écueil, nous verrons en fin de chapitre comment tester le
pictogramme que nous avons choisi. [...]
- conscients.

[...] La première étape de notre travail va consister à vérifier s’il n’existe pas un
pictogramme normalisé sur lequel nous pouvons nous appuyer. Pour obtenir
ce sceau de “norme”, chaque pictogrammes\* doit avoir subi des tests au
niveau mondial, pour les pictogrammes normalisé par l’ISO, ou à l’échelle d’un
continent (norme CE) ou d’un pays (pour la France, AFNOR). [...]
- pictogramme.

Page 59 : 

[...] Pour signifier qu’une protection est apportée, le bouclier est quasiment
systématiquement utilisé. Il s’avère que ces signes font parti\* de la norme ISO
7000:2012 autour des équipements de protection. La construction de ces
signes est telle que la chose dont on est protégé ou à protéger est représentée
au centre. Si nous pouvons représenter les personnes alors nous pourrons en [...]
- partie.

[...] Et même si notre pictogramme nous semble brillant, il est
peut être\* complètement abscons pour la majorité de nos futurs utilisateurs. [...]
- peut-être. // Oui, je suis tatasse.

Page 64 : 

De préparer les entretiens avec les testeurs pour que ceux-ci soient
confrontés à des conditions quasi-réelles\* ;
- Là, j'enlève le tiret.

Page 65 : 

[...] Si nous en avons la possibilité, l’utilisation d’un dispositif d’eye-tracking peut
permettre de collecter les mouvements de la pupille de l’utilisateur et ainsi de
recueillir toutes les interactions que\* nous auraient échappé.
Dans le cadre d’une étude sur un pictogramme, l’investissement s’avère tout
de même très élevé. [...]

*qui. 

Page 66 : 

[...] Le temps de compréhension et les différentes observations que nous auront*
faites lors des tests vont nous permettre d’évaluer les différents
pictogrammes. Ce processus de mise en concurrence est un bon moyen de
voir la pertinence de ceux-ci dans le cas où ils sont des choix. [...]
- aurons.

**Comment by desbenoit** [comment]
Merci ! Nous allons regarder cela en détail. 
Encore une fois, merci pour votre temps !

**Comment by pouipouidesign** [comment]
C'est en cours, merci ! :)

**Comment by pouipouidesign** [comment]
Les corrections ont été apportées et la nouvelle version du livre est en train d'être renvoyée à tous les acheteurs. Merci de votre vigilance et n'hésitez pas si vous en voyez d'autres !
