### ISSUE TITLE
Compréhensions

### ISSUE THREAD

**Issue by P45QU10U** [t13h37/feedback-desbenoit-icones#4]
Page 13, Qui fait quoi :

[...] Il n’est pas facile de se repérer dans ce vocabulaire d’autant plus qu’il varie si
le support de ces signes est imprimé ou un écran\* ! En effet, sur écran nous
utilisons le terme d’icônes. 
- Proposition : ou sur un écran. Je le comprends de cette manière.

Page 27 : 

[...] Mais la possibilité pour l’utilisateur d’interagir avec le support – le clic –
permet de donner une nouvelle fonction aux pictogrammes utilisés sous la
forme d’icônes. L’action de cliquer\* sur une icône provoque une action
correspondant au sens du signe. Ce rôle donné à l’icône s’inscrit dans la
lignée directe de l’utilisation qui en est faite dans la signalétique. [...]
- Parler de clic me semble étrange à ce stade de la lecture. L'informatique seule n'est pas évoquée.
  D'autant plus qu'à ce jour, avec le tactile, on tend à utiliser d'autres termes : La sélection.

Page 63, Tester un pictogramme : 

Les tests sont une étape indispensable.

==> Cette phrase, je la comprends très bien, mais, réaliser des tests est une étape indispensable, je comprends mieux.

Page 70 : 

[...] Nous avons un problème. Lorsque nous travaillons pour écran*, nous ne
calculons pratiquement jamais en millimètres mais presque toujours en pixels
(px). Or le pixel n’est pas stable. Entre le pixel physique dont nous servons
pour concevoir une image (qui mesure 300 px par 200 px) et le pixel de rendu
à l’écran (pixel css dans le cadre du Web), il peut exister une vraie différence. [...] 
- ==> Pour des écrans ?

**Comment by desbenoit** [comment]
Merci beaucoup pour ces commentaires, ils me semblent tous les trois vraiment pertinents. 
Merci pour votre temps.

**Comment by pouipouidesign** [comment]
Hello.

Pas d'accord avec la première, c'est le support qui est "imprimé" ou "un écran".
Contre-proposition : "d’autant plus qu’il varie selon si ces signes sont imprimés ou sur un écran"

Remarque 2, ok pour moi, je propose donc : 
"Mais la possibilité pour l’utilisateur d’interagir avec le support permet de donner une nouvelle fonction aux pictogrammes utilisés sous la forme d’icônes. L’action de sélectionner une icône provoque une action correspondant au sens du signe. Ce rôle donné à l’icône s’inscrit dans la lignée directe de l’utilisation qui en est faite dans la signalétique."

Remarques 3 et 4, ok aussi, c'est changé.

Une fois que nous sommes tous d'accord, et dès que possible ensuite, nous régénérerons les ePubs et PDFs et les enverrons à tous ceux ayant passé commande.
Nous devons d'abord régler le problème de l'issue #2  ... ;)

**Comment by desbenoit** [comment]
Ok pour les 4 points de mon côté.

**Comment by pouipouidesign** [comment]
@riplay777 toi aussi tu es ok ? comme ça je valide les modifs dans la source avant qu'on regénère tout... merci !

**Comment by P45QU10U** [comment]
Tout est O.K

**Comment by pouipouidesign** [comment]
Les corrections ont été apportées et la nouvelle version du livre est en train d'être renvoyée à tous les acheteurs. Merci de votre vigilance et n'hésitez pas si vous en voyez d'autres !
