### ISSUE TITLE
Coquille

### ISSUE THREAD

**Issue by desbenoit** [t13h37/feedback-desbenoit-icones#5]
(Repérée par Stéphane Deschamps) 

Chapitre 2, dernier paragraphe. 
« Nous retrouvons des icônes surtout nos objets » 
-> 
« Nous retrouvons des icônes sur tout nos objets »

**Comment by pouipouidesign** [comment]
Je dirai même "**sur tous** nos objets" ;)

**Comment by desbenoit** [comment]
Oups...
