### ISSUE TITLE
Dans "New Downloads for Order ###", il manque un mot

### ISSUE THREAD

**Issue by borisschapira** [t13h37/feedback-desbenoit-icones#6]
Hello,

Quand on reçoit un mail pour le téléchargement, il est écrit dedans 

> This link may be used up to times before it expires on forever

Je crois qu'il manque un nombre avant "times", pour dire combien de fois on peut utiliser le lien de download. Ça où je ne comprends pas la phrase (ce qui est possible).

**Comment by pouipouidesign** [comment]
Hello ! Tu as raison, le template en question n'est pas correct... je vais regarder ça au plus vite !
Merci :)

**Comment by pouipouidesign** [comment]
Ok, après un coup d'oeil, tous les templates sont maintenant traduits en français avec le bon texte.
En effet, le texte aurait dû être "Ce lien peut être utilisé autant de fois que vous le voulez, sans date d'expiration.", ce qui est beaucoup mieux :)
