### ISSUE TITLE
Coquille

### ISSUE THREAD

**Issue by borisschapira** [t13h37/feedback-desbenoit-icones#7]
> Ce qui va compter, c’est le travail de recherche en amont **effectué fait** par les disciples des deux écoles.

Et sinon, à un moment, Sébastien parle des 3 signes de géolocalisation de Microsoft, Google et Apple, je me suis demandé s'il était voulu de ne pas les reproduire ou si c'était une omission.

J'ai vu d'autres coquilles, mais elles ont déjà été corrigées dans une mise-à-jour, GG !

**Comment by pouipouidesign** [comment]
Hello Boris, merci pour ta vigilance ! La coquille a été corrigée et sera présente dans la prochaine mise à jour à venir bientôt :)

Pour la question à propos des signes de géolocalisation, je laisse @desbenoit te répondre mais il ne me semble pas qu'il y ai d'erreur par rapport à la source, en tout cas.

**Comment by desbenoit** [comment]
Je viens de relire et c'est effectivement mieux avec : 
Légende : les icônes de géolocalisation (dans l'ordre) d'Apple, de Nokia et de Google. 
![geolocations](https://cloud.githubusercontent.com/assets/1142531/3669233/5486bfa6-1230-11e4-9e39-08c1592df23c.png)

**Comment by pouipouidesign** [comment]
Merci Sébastien, mais tu pourrai faire un pull-request avec la bonne image au bon endroit stp ?
A minima, pourrais-tu nous fournir le .svg pour que je m'occupe de l'insertion dans le livre moi-même ?

**Comment by desbenoit** [comment]
Pas de soucis pour le PR mais je n'ai pas accès au repo.

## 

Sébastien Desbenoit

**Comment by pouipouidesign** [comment]
Si-si, je t'ai donné accès au repo du livre sur bitbucket :)

**Comment by desbenoit** [comment]
Vu, merci beaucoup.

## 

Sébastien Desbenoit

2014-07-23 10:21 GMT+02:00 Marie Alhomme notifications@github.com:

**Comment by pouipouidesign** [comment]
Normalement, ceci devrait être réglé avec la dernière mise à jour !
Ne pas hésiter à rouvrir si ce n'est pas le cas :)
