### ISSUE TITLE
La svastika est toujours dans le même sens dans l'extrait PDF

### ISSUE THREAD

**Issue by tut-tuuut** [t13h37/feedback-desbenoit-icones#8]
Bonjour ! Chouette idée, les retours dans le bug tracker de github. :)

J'ai ouvert l'extrait PDF du livre dans le visualiseur PDF de Firefox (v. 32), et j'ai vu ceci à la page 12 : 

![screenshot 2014-10-06 a 10 46 22](https://cloud.githubusercontent.com/assets/1035145/4523277/6f40f790-4d35-11e4-9faa-ab66dd154155.png)

Je n'ai pas l'impression de voir deux svastikas différentes. Pourtant le texte donne l'impression qu'il y en a 2 versions.

J'ai alors téléchargé le fichier sur mon disque dur et je l'ai ouvert avec Preview (Mac os X 10.9.4) et ce n'était pas beaucoup plus convaincant : 
![screenshot 2014-10-06 a 10 51 33](https://cloud.githubusercontent.com/assets/1035145/4523335/020c8a30-4d36-11e4-9d75-596b70e795ed.png)

Peut-être faudrait-il remplacer le signe typographique par une simple image ? (Enfin, _les_ signes par _des_ images…)

**Comment by pouipouidesign** [comment]
Bonjour,

Merci pour ton commentaire et ravis que passer par Github te semble pratique :)

Bien vu pour le problème, nous l'avions déjà décelé il y a un bout de temps, et corrigé (effectivement avec des images), mais par contre nous avons dû oublier de mettre à jour l'extrait sur la boutique (la copie sur le repo étant bonne)...

Bref, je viens d'uploader la bonne version, normalement tout devrait être rentré dans l'ordre !

Encore merci pour ta vigilance, en espérant que le livre te plaira (parce que tu vas l'acheter du coup, hein, hein ? :)) !
